FROM python:3.8.16-slim

# set environment variables
ENV PATH="/usr/local/bin:$PATH"
ENV LANG="C.UTF-8"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
# set work directory
WORKDIR /usr/src/app

COPY ./setup.py /tmp/setup.py

# install git
RUN apt-get update && apt-get install git -y

RUN apt-get install ffmpeg libsm6 libxext6  -y\
    && pip install --upgrade --no-cache-dir pip setuptools wheel  

RUN pip install --no-cache-dir torch==2.3.1+cpu torchvision==0.18.1+cpu -f https://download.pytorch.org/whl/torch_stable.html 

COPY ./src/requirements-light.txt /tmp/requirements.txt
RUN pip install --default-timeout=500 -r /tmp/requirements.txt \
    && pip cache purge \
    && rm -rf /root/.cache/pip

RUN pip install --no-cache-dir git+https://github.com/pyronear/pyro-api.git@92b9e28fe4b329aa28c7833b28f3bc89ab1b756c#subdirectory=client

COPY ./pyroengine /tmp/pyroengine

RUN pip install -e /tmp/. \
    && pip cache purge \
    && rm -rf /root/.cache/pip

COPY ./src/run.py /usr/src/app/run.py
COPY ./src/control_reolink_cam.py /usr/src/app/control_reolink_cam.py
