services:
  pyro-camera-api:
    build:
      context: ./pyro_camera_api
    image: pyronear/pyro-camera-api:${PYRO_ENGINE_VERSION:-latest}
    container_name: pyro-camera-api
    environment:
      CAM_USER: ${CAM_USER}
      CAM_PWD: ${CAM_PWD}
      MEDIAMTX_SERVER_IP: ${MEDIAMTX_SERVER_IP}
      ENABLE_STUCK_DETECTOR: ${ENABLE_STUCK_DETECTOR:-true}
    volumes:
      - ./data:/usr/src/app/data
    restart: always
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8081/health || exit 1"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"


  engine:
    build:
      context: ./engine
    image: pyronear/pyro-engine:${PYRO_ENGINE_VERSION:-latest}
    container_name: engine
    environment:
      API_URL: ${API_URL}
      CAM_USER: ${CAM_USER}
      CAM_PWD: ${CAM_PWD}
    volumes:
      - ./data:/usr/src/app/data
    command: >
      sh -c '
        truncate -s 0 engine.log &&
        python run.py 2>&1 | tee -a engine.log
      '
    restart: always
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "grep -q 'confidence\\|Nighttime detected' engine.log || exit 1"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
