[tool.poetry]
name = "pyroengine"
version = "0.1.0"
description = "Wildfire detection on edge devices"
authors = ["Pyronear <contact@pyronear.org>"]
readme = "README.md"
license = "Apache-2.0"
keywords = ["pytorch", "deep learning", "vision", "cnn", "wildfire"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
requests = ">=2.20.0,<3.0.0"
tqdm = ">=4.62.0"
aiohttp = "==3.11.18"
onnxruntime = "==1.18.1"
huggingface_hub = "==0.23.1"
pillow = "==11.0.0"
ncnn = "==1.0.20240410"
pyroclient = {git = "https://github.com/pyronear/pyro-api.git", branch = "main", subdirectory = "client"}

[tool.poetry.extras]
test = [
    "pytest",
    "pytest-asyncio",
    "coverage",
    "python-dotenv",
    "onnx",
]
quality = [
    "flake8",
    "isort",
    "mypy",
    "pydocstyle",
    "black",
]
docs = [
    "sphinx",
    "furo",
    "sphinxemoji",
    "sphinx-copybutton",
    "Jinja2",
]
dev = [
    "pytest",
    "pytest-asyncio",
    "coverage",
    "requests",
    "flake8",
    "isort",
    "mypy",
    "pydocstyle",
    "black",
    "sphinx",
    "furo",
    "sphinxemoji",
    "sphinx-copybutton",
    "Jinja2",
]


[tool.poetry.urls]
documentation = "https://pyronear.org/pyro-engine"
repository = "https://github.com/pyronear/pyro-engine"
tracker = "https://github.com/pyronear/pyro-engine/issues"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

# Optional: you can keep these too
[tool.setuptools]
zip-safe = true

[tool.setuptools.packages.find]
exclude = ["docs*", "scripts*", "tests*", "src*"]

[tool.mypy]
files = "pyroengine/"
show_error_codes = true
pretty = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
check_untyped_defs = true
implicit_reexport = false

[[tool.mypy.overrides]]
module = [
    "onnxruntime.*",
    "requests.*",
    "PIL.*",
    "pyroclient.*",
    "urllib3.*",
]
ignore_missing_imports = true

[tool.isort]
line_length = 120
src_paths = ["pyroengine", "tests", "src", "docs", ".github", "scripts"]
skip_glob = "**/__init__.py"

[tool.pydocstyle]
select = "D300,D301,D417"
match = ".*\\.py"

[tool.coverage.run]
source = ["pyroengine"]

[tool.black]
line-length = 120
target-version = ['py39']
