srt_settings:
  host: 91.134.47.14     # SRT receiver public IP or DNS
  pkt_size: 1316
  mode: caller
  latency: 50
  port_start: 8890
  streamid_prefix: publish

ffmpeg_params:
  discardcorrupt: true
  low_delay: true
  rtsp_transport: tcp
  video_codec: libx264
  b_frames: 0
  gop_size: 5
  bitrate: 500k
  framerate: 10
  preset: veryfast
  tune: zerolatency
  threads: 1
  audio_disabled: true
  output_format: mpegts
  x264_params: "scenecut=40:rc-lookahead=0:ref=3"
  pix_fmt: yuv420p
