srt_settings:
  pkt_size: 1316              # Packet size in bytes, ideal for MPEG TS
  mode: caller                # Sender initiates the connection
  latency: 50                 # Buffer in milliseconds for stability
  port_start: 8890            # First SRT port used for streams
  streamid_prefix: publish    # Prefix to build the stream ID

ffmpeg_params:
  discardcorrupt: true        # Drop damaged packets, keep buffers small
  low_delay: true             # Prefer minimal latency behavior
  rtsp_transport: tcp         # RTSP over TCP for reliability
  video_codec: libx264        # H.264 video encoding via x264
  b_frames: 0                 # Use only I and P frames for low latency
  gop_size: 10                # One second GOP at ten fps
  bitrate: 500k               # Target video bitrate
  framerate: 10               # Frames per second
  preset: veryfast            # Encoder speed preset
  tune: zerolatency           # Encoder tuning for low latency
  threads: 1                  # Single thread for stable timing
  audio_disabled: true        # Disable audio track
  output_format: mpegts       # Container suited for SRT

  analyzeduration: "1M"       # Probe time budget, about one second
  probesize: "2M"             # Probe size budget in bytes
  stimeout_us: 5000000        # RTSP socket timeout in microseconds

  use_crf: false              # Use constant bitrate mode
  bufsize: "100k"             # VBV buffer size for rate control
