srt_settings:
  pkt_size: 1316              # Packet size in bytes, ideal for MPEG TS
  mode: caller                # Sender initiates the connection
  latency: 50                 # Buffer in milliseconds for stability
  port_start: 8890            # First SRT port used for streams
  streamid_prefix: publish    # Prefix to build the stream ID

ffmpeg_params:
  discardcorrupt: true
  low_delay: true
  rtsp_transport: tcp
  video_codec: libx264
  b_frames: 0
  framerate: 7
  gop_size: 14                  # encoder keyint in frames, about two seconds
  bitrate: 700k                 # encoder target after anonymization
  preset: veryfast
  tune: zerolatency
  threads: 1
  audio_disabled: true
  output_format: mpegts

  analyzeduration: "1M"
  probesize: "2M"
  stimeout_us: 5000000

  use_crf: false
  bufsize: "800k"
  maxrate: "900k"
  pix_fmt: "yuv420p"
  x264_params: "keyint=14:min-keyint=7:scenecut=40:rc-lookahead=0:ref=2:aq-mode=2"
