srt_settings:
  pkt_size: 1316
  mode: caller
  latency: 30          # try 30 first, then 20 if the link is clean
  rcvlatency: 30
  peerlatency: 30
  tlpktdrop: 1         # drop late packets to protect latency

ffmpeg_params:
  discardcorrupt: true
  low_delay: true
  rtsp_transport: tcp

  framerate: 10        # or 12, this reduces the latency floor
  gop_size: 10         # keep about one second GOP
  video_codec: libx264
  preset: veryfast
  tune: zerolatency

  # allow intra frame parallelism, but keep one frame in flight
  threads: 8           # set to your core count
  x264_params: "keyint=10:min-keyint=10:scenecut=0:rc-lookahead=0:ref=1:aq-mode=2:frame-threads=1:sliced-threads=1"

  # rate control, small VBV to avoid extra buffering
  use_crf: false
  bitrate: 700k
  maxrate: "750k"
  bufsize: "150k"

  # make the muxer strict
  output_format: mpegts
  mpegts_flags: "resend_headers"
  muxdelay: "0"
  muxpreload: "0"

  # startup and read behavior
  analyzeduration: "0"
  probesize: "32k"
  stimeout_us: 5000000

  # timestamps and pixel format
  pix_fmt: "yuv420p"
  genpts: true
  wallclock_ts: true     # same as -use_wallclock_as_timestamps 1
  nobuffer: true         # same as -fflags nobuffer
