server:
  http_listen_port: 8300

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      scope: ${PROMTAIL_TOWER_SCOPE}
      tower: ${PROMTAIL_TOWER_NAME} 
      __path__: /var/lib/docker/containers/*/*log
