name: docs
on:
  push:
    branches: main

jobs:
  docs-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.11']
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Cache python modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}-docs
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Stub version.py for docs
        run: |
          echo "__version__ = '0.0.0'" > pyroengine/version.py
      
      - name: Install documentation dependencies
        run: |
          poetry install --with docs
        
      - name: Build documentation
        run: sphinx-build docs/source docs/build -a -v

      - name: Documentation sanity check
        run: test -e docs/build/index.html || exit

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: 'docs/build'
          COMMIT_MESSAGE: '[skip ci] Documentation updates'
          CLEAN: true
          SSH: true
