name: style

on:
  push:
    branches: main
  pull_request:
    branches: develop

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.5.13"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install quality dependencies
        run: uv sync --only-group quality
      - name: Run ruff
        run: |
          uv run ruff --version
          uv run ruff format --check --diff .
          uv run ruff check --diff .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install quality dependencies
        run: uv sync --group quality
      - name: Run mypy
        run: |
          uv run mypy --version
          uv run mypy
